travis:
  secure:
    BINSTAR_TOKEN: nFCwFEZ5c6qrNMsmYe9eUGEtWPcsBVMdIogXNfeMOi6JJz+Q8kpHp1lbFZQJxM582rC2yPzU2mEqP/FI/0JsEYPI+N4ntfnQXU6ljGvJcXwFGU+VDmMtoBSG8Lrv4CI+Cl4a+yKhZi/nSvZ04cwj2FWzf7P2mRajA4A4bCDWmvIgx6UjMabbvb7eoJRWLLxHw2S/4V/yL2QKVj+KOVvxy3cfJMJaEuzxk5Nv21qQZldLHOggP4hCmUggYSRxvtqQAuH99TE13N3KMRgEAjW2qKe4eR/ULlrXzRfuAm2bnoI9Dyzx+m8QWL9AHAc4+HErtyVxlFyp6D4UUr6bQci9Kh3zi8iYVE5MKfui7aGEekJf/2SPOsZsS3KV1KI1O5cI3DF5bJycET77wut8FTfFInq/JLqaqbK3gK72lgvE7Oa5lEn3dLab3gCKWi8Y1rIwNYs/ypuEN0fSxElnJrpT1YYsfn1jF+ADfa/3rzKE25tWttev7hLXTNZ1P3jlEbBF6T//p3gSIv3tithaWoyx/b30tJ6f0mjzk03QV2CymU3bck7vxlrWTD1zlx5FqdZ1Y495sI6/C3FsVUrYJN5NVEP5obcKvREFCxvK84tb4MfdKgYn14r/M+r+kxxtFjBMEhWJulm3HOhAwhs2P9GTQ+c6kGLCe0l//B2al+CVsrA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
